sudo: required
dist: trusty
language: generic

branches:
  except:
    - gh-pages

env:
  # This will check any ROS distro with any python interpreter
  # supported on this OS

  # Disabling ROS workflow checks since pyros_setup should be used only with pip dependencies, only when catkin is not available.
  # => making a ROS package from it is not supported (and not needed anyway).
  - CI_ROS_DISTRO=indigo PYTHON=2.7
  - CI_ROS_DISTRO=indigo PYTHON=3.4

  - CI_ROS_DISTRO=jade PYTHON=2.7
  - CI_ROS_DISTRO=jade PYTHON=3.4
  # TODO : kinetic + docker
  # TODO : pypy + pypy3

# We need to get a ROS distro to be able to test pyros-setup
# from different virtualenv using site-packages.
before_install:
  # Install ROS. We always need it for testing on system, even if we are in a virtualenv.
  - bash rosutils/install_ros.sh
  # Install python and required packages on system if needed
  - sudo apt-get install python${PYTHON} virtualenvwrapper -y && source "/usr/share/virtualenvwrapper/virtualenvwrapper.sh"

install:
  - mkvirtualenv --system-site-packages -i . -q python_${PYTHON}_ros

script:
  - workon python_${PYTHON}_ros && pyros_setup --pytest --distro ${CI_ROS_DISTRO}

notifications:
  email: false
