sudo: required
dist: trusty
language: python

branches:
  except:
    - gh-pages

python:
  - 2.7
  - 3.4
  #- pypy
  #- pypy3

env:
  # This will check any ROS distro supported on this OS
  - DISTRO=indigo
  - DISTRO=jade

# We need to get a ROS distro to be able to test pyros-setup
# from different virtualenv using site-packages.
before_install:
  # Install ROS. We always need it on system.
  - bash rosutils/install_ros.sh
  # Install package ROS dependencies (needed until we can package a standard python deb for pyros-setup. see https://github.com/asmodehn/pyros-setup/issues/16)
  - rosdep install --default-yes --from-paths ./ --rosdistro $DISTRO

install:
  # we need recent tox
  - pip install tox tox-travis --upgrade

script:
  # Tox doesn't work currently (doesnt include dist-packages in its venvs path for some reason...)
  # - tox
  - python setup.py develop
  - py.test pyros_setup --distro $DISTRO

notifications:
  email: false
