sudo: required
dist: trusty
# this will setup everything needed for our python environments
language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests

#this install all the ROS stuff
before_install:
  - export CI_ROS_DISTRO=indigo
  - echo $CI_ROS_DISTRO
# Add ROS repositories
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
# Install and initialize rosdep
  - sudo apt-get install python-rosdep -y
  - sudo `which rosdep` init
  - rosdep update
# Use rosdep to install pyros-setup's dependencies
  - rosdep install --default-yes --from-paths ./ --rosdistro $CI_ROS_DISTRO

# Installing pip dependencies in the provided virtualenv
install:
  - pip install -q -r requirements.txt
  - pip install -q -e .

script:
# The main thing : python package tests
  - python setup.py test

#
# full ROS setup, build and test, to make sure it will still work for ROS development
#
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=./install
  - make -j1
# make sure we get devel version and run tests on it
  - source devel/setup.bash
  - make -j1 tests
  - make -j1 run_tests
  - catkin_test_results .
  - make -j1 install
# now using installed version and testing
  - source install/setup.bash
  - nosetests pyros_setup.tests
notifications:
  email: false
