sudo: required
dist: trusty
language: generic

branches:
  except:
    - gh-pages

env:
  # This will check any ROS distro with any python interpreter
  # supported on this OS
  - DISTRO=indigo
  - DISTRO=indigo PYTHON=2.7
  - DISTRO=indigo PYTHON=3.4
  - DISTRO=jade
  - DISTRO=jade PYTHON=2.7
  - DISTRO=jade PYTHON=3.4
  # TODO : pypy + pypy3

# We need to get a ROS distro to be able to test pyros-setup
# from different virtualenv using site-packages.
before_install:
  # Install ROS. We always need it for testing on system.
  - bash rosutils/install_ros.sh
  # Install python and required packages on system if needed
  - if [ -z ${PYTHON+undef} ]; then echo "Python virtual env not used"; else sudo apt-get install python${PYTHON} virtualenvwrapper -y && source "/usr/share/virtualenvwrapper/virtualenvwrapper.sh"; fi
  # Install package ROS dependencies (needed until we can package a standard python deb for pyros-setup. see https://github.com/asmodehn/pyros-setup/issues/16)
  - rosdep install --default-yes --from-paths ./ --rosdistro $DISTRO

install:
  - if [ -z ${PYTHON+undef} ]; then (bash rosutils/build_devel.sh $DISTRO && bash rosutils/build_install.sh); else (mkvirtualenv --system-site-packages -r requirements.txt -i . -q python_${PYTHON}_ros); fi

script:
  - if [ -z ${PYTHON+undef} ]; then (bash rosutils/test_devel.sh && bash rosutils/test_install.sh); else (workon python_${PYTHON}_ros && python setup.py develop && py.test --pyargs pyros_setup); fi

notifications:
  email: false
