sudo: required
dist: trusty

before_install:
# Install our ROS stuff
  - bash rosutils/install_ros.sh indigo ./
# Install our python dependencies
  - sudo apt-get install python2.7 virtualenvwrapper -y

install:
  # Making a virtualenv for python 2.7 and installing pip dependencies and package in it
  - mkvirtualenv --system-site-packages python_2.7_ros
  - workon python_2.7_ros
  - pip install -q -r requirements.txt
  - pip install -q .
  - deactivate

# Make sure build works for ROS
  - bash rosutils/build_devel.sh indigo
  - bash rosutils/build_install.sh

script:
# The main thing : python package tests in virtualenv
  - workon python_2.7_ros
  - python setup.py test
  - deactivate
# Make sure we get devel version and run tests on it
  - bash rosutils/test_devel.sh
# Now using installed version and testing
  - bash rosutils/test_install.sh

notifications:
  email: false
